apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssme-app-api-deployment
  labels:
    service-name: ssme-app-api
    app-name: ssme-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service-name: ssme-app-api
      app-name: ssme-app
  template:
    metadata:
      labels:
        service-name: ssme-app-api
        app-name: ssme-app
    spec:
      containers:
        - name: ssme-app-api
          image: de.icr.io/ssme-app/ssme-app-api:0.0.5
          imagePullPolicy: Always
          env:
            - name: MAX_CHARS_TO_SYNTHESIZE
              value: '50'
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /opt/service-bind
              name: service-bind-volume
              readOnly: true
      imagePullSecrets:
        - name: ssme-app-de-icr-io
      volumes:
        - name: service-bind-volume
          secret:
            defaultMode: 420
            secretName: binding-texttospeech
