apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssme-app-fe-deployment
  labels:
    service-name: ssme-app-fe
    app-name: ssme-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service-name: ssme-app-fe
      app-name: ssme-app
  template:
    metadata:
      labels:
        service-name: ssme-app-fe
        app-name: ssme-app
    spec:
      containers:
        - name: ssme-app-api
          image: de.icr.io/ssme-app/ssme-app-fe:0.0.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: ssme-app-de-icr-io
