apiVersion: v1
kind: Service
metadata:
  name: ssme-app-fe-service
  labels:
    service-name: ssme-app-fe
    app-name: ssme-app
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30085       
  selector:
    service-name: ssme-app-fe
    app-name: ssme-app
